### ISSUE TITLE
how can i add subtitle on a video

### ISSUE THREAD

**Issue by AGPEIM** [a-schild/jave2#145]
I have a subtitle file in ass format, how can I add it to the video?

**Comment by a-schild** [comment]
I have not tested it myself, but you should be able to use the generic Filter for this, just use addNamedArgument("ass", "subtitle.ass")

https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo

Would be cool if you create a SubtitleFilter class and a test case and submit it as a pull request to the project

**Comment by AGPEIM** [comment]
thanks for your help ,I tried sometime like this, but it seems doesn't work
```
        Encoder encoder=new Encoder();
        EncodingAttributes attributes=new EncodingAttributes();
        AudioAttributes audioAttributes=new AudioAttributes();
        VideoAttributes videoAttributes=new VideoAttributes();

        audioAttributes.setCodec(AudioAttributes.DIRECT_STREAM_COPY);
        videoAttributes.setCodec(VideoAttributes.DIRECT_STREAM_COPY);
        Filter filter=new Filter("subtitleFilter");
        filter.addNamedArgument("ass",subtitle.getAbsolutePath());
        videoAttributes.addFilter(filter);

        attributes.setAudioAttributes(audioAttributes);
        attributes.setVideoAttributes(videoAttributes);
        try {
            encoder.encode(new MultimediaObject(video),targetVideo,attributes);
        } catch (EncoderException e) {
            e.printStackTrace();
        }
```
When I run it, it reports the following error

```
ws.schild.jave.EncoderException: Exit code of ffmpeg encoding run is 1
	at jave.core@3.0.1/ws.schild.jave.Encoder.encode(Encoder.java:572)
	at jave.core@3.0.1/ws.schild.jave.Encoder.encode(Encoder.java:351)
	at jave.core@3.0.1/ws.schild.jave.Encoder.encode(Encoder.java:318)
```

**Comment by a-schild** [comment]
Could you please attach the ass file here?
And can you turn on debug logging and see what commandline is used fo ffmpeg?

**Comment by AGPEIM** [comment]
It looks like it'sFFmpeg‘s problem
I learned from [this](https://zhuanlan.zhihu.com/p/161000532) ) article(which is write in Chinese) that when there is a disk character in the path of the subtitle, it will cause an error. He gave me the solution, which I could use in CMD, but it didn't work in PowerShell. 
the same code `ffmpeg  -i C:\Users\41388\1.mp4  -vf subtitles=\'c:/Users/41388/Desktop/1.ass\' 1.mp4` has different results
![image](https://user-images.githubusercontent.com/37290414/115367908-2be09800-a1f9-11eb-9f35-92ef4c20d973.png)
Also, it is not valid to use in Java.
```
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 18 message: <[subtitles @ 0000016bf0c53740] Unable to parse option value "/Users/41388/Desktop/1.ass" as image size>
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 20 message: <[subtitles @ 0000016bf0c53740] Error setting option original_size to value /Users/41388/Desktop/1.ass.>
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 21 message: <[Parsed_subtitles_0 @ 0000016bf0a52ec0] Error applying options to the filter.>
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 22 message: <[AVFilterGraph @ 0000016befc424c0] Error initializing filter 'subtitles' with args 'filename=c:/Users/41388/Desktop/1.ass'>
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 23 message: <Error reinitializing filters!>
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 24 message: <Failed to inject frame into filter network: Invalid argument>
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 25 message: <Error while processing the decoded data for stream #0:0>
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 26 message: <Conversion failed!>
```

**Comment by a-schild** [comment]
Could you please try with this class:


```
package ws.schild.jave.filters;

import java.io.File;

public class AssSubtitleFilter extends Filter {

  public AssSubtitleFilter(File source) {
    super("ass");
    /*
     * Need escaping special characters []\':,;
     */
    addOrderedArgument(escapingPath(source.getAbsolutePath()));
  }

  public AssSubtitleFilter (File source, String outputLabel) {
    this(source);
    addOutputLabel(outputLabel);
  }

  /**
   *  escaping special characters for file path. <a hrer="https://ffmpeg.org/ffmpeg-filters.html#Notes-on-filtergraph-escaping">Notes on filtergraph escaping</a>
   *
   * @param filePath unescaped file path
   * @return escaped file path
   */
  private String escapingPath(String filePath) {
    return filePath.replaceAll("\\\\","\\\\\\\\")
            .replaceAll("\\[", "\\\\[")
            .replaceAll("]", "\\\\]")
            .replaceAll("'", "\\\\\\\\\\\\'")
            .replaceAll(":","\\\\\\\\:")
            .replaceAll(",","\\\\,")
            .replaceAll(";","\\\\;");
  }
}

```

**Comment by a-schild** [comment]
It's a "clone" of the MovieFilter class

**Comment by AGPEIM** [comment]
sadly it doesn't work...
` <[AVFilterGraph @ 000001f64c012580] Error initializing filter 'ass' with args 'C\\:\\Users\\41388\\Desktop\\VIDEO_20210414_111805_1618569994194.ass'>`

**Comment by a-schild** [comment]
Could you please attach a valid .ass file?

**Comment by AGPEIM** [comment]
GitHub does not support uploading ass files,so I put it in a zip file.
[testAss.zip](https://github.com/a-schild/jave2/files/6342642/testAss.zip)

**Comment by AGPEIM** [comment]
it works in the following way, but only if the subtitle file is on disk C (where the FFmpeg.exe is located).
```
private String escapingPath(String filePath) {
        filePath=filePath.replaceAll("\\\\","/");
        filePath=filePath.split(":")[1];
        return filePath;
    }
```

**Comment by a-schild** [comment]
Can you please try with the 3.2.0-SNAPSHOT relase and the ws.schild.jave.filters.AssSubtitlesFilter class?

**Comment by AGPEIM** [comment]
It works! really really appreciate it！

**Comment by qq1440837150** [comment]
> 3.2.0-SNAPSHOT

how can i get this version? i can not find it in maven repository.

**Comment by AGPEIM** [comment]
> > 3.2.0-SNAPSHOT
> 
> how can i get this version? i can not find it in maven repository.

作者还没有发正式版吧，如果是maven项目的话应该启用SNAPSHOT。你可以参考[这个](https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository)，或者直接在pom.xml里添加
```
    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>

```

**Comment by qq1440837150** [comment]
多谢
