### ISSUE TITLE
aarch64是否可以支持使用？

### ISSUE THREAD

**Issue by 18279435013** [a-schild/jave2#193]
我的服务器是aarch64的，在使用过程中提示错误信息，ffmep-aarch64缺失。

**Comment by a-schild** [comment]
Eglish please

**Comment by a-schild** [comment]
In the 3.3.0-SNAPSHOT version we have a jave-nativebin-osxm1 which supports the M1 chip

**Comment by dr-slurp** [comment]
> 

When does the 3.3.0-snapshot come out?

I'm getting similar errors on my 2022 M1 MAX macbook pro. The same code works just fine on my old 2014 mac book pro. The errors look like:
`Exception in thread "main" ws.schild.jave.EncoderException: java.io.IOException: Cannot run program "/var/folders/t3/d0344lf14fs00nhhb6rphvfc0000gn/T/jave/ffmpeg-aarch64-3.2.0-osx": error=2, No such file or directory
	at ws.schild.jave.Encoder.encode(Encoder.java:508)
	at ws.schild.jave.Encoder.encode(Encoder.java:351)
	at ws.schild.jave.Encoder.encode(Encoder.java:318)
	at dr_slurp.MyceliumFidelity.Video.VideoSplitter.split(VideoSplitter.java:46)
	at dr_slurp.MyceliumFidelity.MyFiTester.main(MyFiTester.java:19)`

Thanks for the help.

**Comment by hramberger** [comment]
Similar Story here:

```
ERROR [main] w.s.j.p.f.DefaultFFMPEGLocator: Could not find ffmpeg platform executable in resources for <ws/schild/jave/nativebin/ffmpeg-aarch64-osx>
ERROR [main] w.s.j.p.f.DefaultFFMPEGLocator: ffmpeg executable NOT found: /var/folders/vw/xqbw628j2sggf3y98370qhb80000gn/T/jave/ffmpeg-aarch64-3.2.0-osx
```

**Comment by hramberger** [comment]
I updated `jave-all-deps` to the newly released version `3.3.0`, but unfortunately I still get the same error. I suspect a naming mismatch between the package name (`osxm1`) and the name the `DefaultFFMPEGLocator` is looking for (`ffmpeg-aarch64-3.3.0-osx`).

**Comment by dr-slurp** [comment]
Damn. So close but so far. Soon....

**Comment by a-schild** [comment]
Can you please try with the 3.3.1-SNAPSHOT release of the jave-nativebin-osxm1 (Instead of the jave-all-deps)
The ffmpeg filed had an underlin ein the name, instead of the -

**Comment by hramberger** [comment]
Is the the SNAPSHOT published? I tried to include the following, but maven is unable to resolve it:

```xml
        <dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-nativebin-osxm1</artifactId>
            <version>3.3.1-SNAPSHOT</version>
        </dependency>
```

**Comment by a-schild** [comment]
Have you added the snapshot respository to your pom.xml file?

From here https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository

```
<repositories>
    <repository>
      <id>oss.sonatype.org-snapshot</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
```

**Comment by hramberger** [comment]
@a-schild thanks for the hint. With the correct configuration I was able to download the SNAPSHOT. For me this version works like a charm with a M1 macbook.
