### ISSUE TITLE
Cannot add audio (.wav) to a video file (.mp4)

### ISSUE THREAD

**Issue by dr-slurp** [a-schild/jave2#204]
Hey! Overall I love jave, had tons of luck with splitting .mp4s. Now I need to add audio to my video files. 

`attributes = new EncodingAttributes();
		attributes.setOutputFormat("mp4");
		attributes.setVideoAttributes(video);
		attributes.setAudioAttributes(audio);
		
		MultimediaObject originalVideo = new MultimediaObject(new File(pathToVideo));
		MultimediaObject originalAudio = new MultimediaObject(new File(pathToAudio));
		ArrayList<MultimediaObject> sources = new ArrayList<MultimediaObject>();
		sources.add(originalVideo);
		sources.add(originalAudio);
		
		File target = new File(pathToCombined);

		
		encoder.encode(sources, target, attributes);`

and I'm getting a  
`Exception in thread "main" ws.schild.jave.EncoderException: Exit code of ffmpeg encoding run is 1
	at ws.schild.jave.Encoder.encode(Encoder.java:638)
	at ws.schild.jave.Encoder.encode(Encoder.java:481)
	at ws.schild.jave.Encoder.encode(Encoder.java:324)
	at dr_slurp.MyceliumFidelity.Video.VideoSplitter.addAudioToVideo(VideoSplitter.java:92)
	at dr_slurp.MyceliumFidelity.MyFiTester.audioAdder(MyFiTester.java:34)
	at dr_slurp.MyceliumFidelity.MyFiTester.main(MyFiTester.java:26)
`

Is there a way to put audio on a video file that has no audio already?

Thanks,

**Comment by dr-slurp** [comment]
FYI, I am able to do add audio to the video if I use this command in the CLI:
`ffmpeg -i v.mp4 -i a.wav -c:v copy -map 0:v:0 -map 1:a:0 new.mp4
`
Is there a way to run arbitrary ffmpeg commands from jave2, or a way to run a similar command programatically?

THANKS!

**Comment by wxyleo** [comment]
I also wanna to implement it, but i don't find any method.
so sad..

**Comment by dr-slurp** [comment]
@wxyleo 
This is how i'm doing it without jave2, good luck

`
		
		Runtime rt = Runtime.getRuntime();
		Process pr = rt.exec("/opt/homebrew/bin/ffmpeg -i "+pathToVideo+" -i "+pathToAudio+" -c:v copy -map 0:v:0 -map 1:a:0 "+pathToCombined);

		BufferedReader stdInput = new BufferedReader(new InputStreamReader(pr.getInputStream()));
		BufferedReader stdError = new BufferedReader(new InputStreamReader(pr.getErrorStream()));
		
		String s = null;
		while ((s = stdInput.readLine()) != null) 
		{
		    System.out.println(s);
		}

		// Read any errors from the attempted command
		System.out.println("Here is the standard error of the command (if any):\n");
		while ((s = stdError.readLine()) != null) {
		    System.out.println(s);
		}
		
		
//		Process pr = rt.exec("/opt/homebrew/bin/ffmpeg");
		System.out.println(pr.getOutputStream().toString());
		int result = pr.waitFor();
		if(result == 0)
		{
			System.out.println("success");
		}`

**Comment by wxyleo** [comment]
tks

**Comment by a-schild** [comment]
Closing this as part of a tidy up before 4.0.0, not because it was judged invalid.

This predates a substantial rework. The bundled ffmpeg has gone from 4.4 to 9.0.1 on every platform, the linux binaries are now built from source and linked statically against musl rather than taken from a publisher, and several long standing faults were fixed along the way, among them `-vol` and `-vsync` being sent to an ffmpeg that had removed them, a race that could run the extracted binary before it was executable, and `getSupportedEncodingFormats` silently returning nothing on any modern ffmpeg.

There is a fair chance the behaviour here is simply gone. There is also no reproducer on file and no way to tell from here.

**If it still happens on 4.0.0, please reopen** — the issue keeps its history and I would rather look at a live problem than leave a years old report sitting open. A short reproducer, the platform, and the exception would be plenty.
