### ISSUE TITLE
Strange error with audio 

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#21]
Today i got this strange error and the fun fact is that i can't reproduce it even with the same variables and audio ... 

```JAVA
ws.schild.jave.EncoderException: In step: 3 Error in line 30 : <[mp3 @ 00000266d57fa660] invalid new backstep -1>
Calculting WAV amplitudes
	at ws.schild.jave.ConversionOutputAnalyzer.analyzeNewLine(ConversionOutputAnalyzer.java:155)
	at ws.schild.jave.Encoder.encode(Encoder.java:530)
	at main.java.com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.transcodeToWav(WaveFormService.java:345)
	at main.java.com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.processFromNoWavFile(WaveFormService.java:190)
	at main.java.com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.call(WaveFormService.java:143)
	at main.java.com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.call(WaveFormService.java:1)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Service.java:725)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by goxr3plus** [comment]
Just managed to reproduce it here is the bugged audio https://ufile.io/ts0rg

**Comment by a-schild** [comment]
Can yopu please post the conversion paramters you are using?

**Comment by goxr3plus** [comment]
Yes : 

You can directly run [this](https://github.com/goxr3plus/Java-Audio-Wave-Spectrum-API/blob/master/src/soundcloud/BoxWaveform.java) code if you like .

I am using the below method ....


```JAVA
/**
 * Transcode to Wav
 * 
 * @param sourceFile
 * @param destinationFile
 * @throws EncoderException
 */
private static void transcodeToWav(File sourceFile , File destinationFile) throws Exception {
	//Attributes atters = DefaultAttributes.WAV_PCM_S16LE_STEREO_44KHZ.getAttributes()
	
	//Set Audio Attributes
	AudioAttributes audio = new AudioAttributes();
	audio.setCodec("pcm_s16le");
	audio.setChannels(2);
	audio.setSamplingRate(44100);
	
	//Set encoding attributes
	EncodingAttributes attributes = new EncodingAttributes();
	attributes.setFormat("wav");
	attributes.setAudioAttributes(audio);
	
	//Encode		s
	new Encoder().encode(new MultimediaObject(sourceFile), destinationFile, attributes);
}
```

**Comment by goxr3plus** [comment]
Wow the new ffmpeg on version 2.4.3 is 60 MB O_o .

**Comment by a-schild** [comment]
2.4.3 includes the 4.x ffmpeg binaries, which are much larger than the 3.x

**Comment by goxr3plus** [comment]
Any advantages we get except of bug fixes here :)?

**Comment by a-schild** [comment]
Two advantages:
- It fixes several know vulnerabilities https://www.ffmpeg.org/security.html
- The output format and the exit status of the process is now more consistent, simplifying parsing

**Comment by goxr3plus** [comment]
Thank you , it seems worthing the 40++ MB .

**Comment by a-schild** [comment]
Hello @goxr3plus , have you tested with the 2.4.3-SNAPSHOT release?
For we the conversion works under win64 with the parameters and file you gave me.

**Comment by a-schild** [comment]
Please use the 2.4.3-SNAPSHOT version (Is also in maven),
if it works fro you I will make the final version
