### ISSUE TITLE
Cannot run program "/tmp/jave/ffmpeg-amd64-3.2.0"

### ISSUE THREAD

**Issue by boyangc** [a-schild/jave2#236]
We deploy on linux.This error occurs :
`java.io.IOException: Cannot run program "/tmp/jave/ffmpeg-amd64-3.2.0": error=13, 权限不够
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:593)
	at java.lang.Runtime.exec(Runtime.java:458)
	at ws.schild.jave.process.ProcessWrapper.execute(ProcessWrapper.java:103)
	at ws.schild.jave.process.ProcessWrapper.execute(ProcessWrapper.java:135)
	at com.alipay.zark.avatar.service.FileUploadServer.ffmpegExecut(FileUploadServer.java:464)
	at com.alipay.zark.avatar.service.FileUploadServer.generateBackgroundImage(FileUploadServer.java:686)
	at com.alipay.zark.avatar.service.FileUploadServer.afterProcess(FileUploadServer.java:340)
	at com.alipay.zark.avatar.service.FileUploadServer.onMessage(FileUploadServer.java:130)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:703)
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:963)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:887)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1096)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1077)
Caused by: java.io.IOException: error=13, 权限不够
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)`

**Comment by a-schild** [comment]
Is that file existing in /tmp/jave/ folder?
Is it executable by the user which the server is running under?

**Comment by boyangc** [comment]
> Is that file existing in /tmp/jave/ folder? Is it executable by the user which the server is running under?

and i have chown 777 , but it not works

**Comment by boyangc** [comment]
> Then you have to look at your server envrionemnt, Perhaps some SELINUX settings or similar blocking the executable

i find that it fails in /tmp/  directory, but when i copied ffmpeg-amd54-3.2.0 to /data/ directory ,  it is executable. 
So how do I specify the location where the ffmpeg file is generated or the location my program call when use ffmpeg in the system? I didn't do anything at the beginning, it was to automatically generate ffmpeg in /tmp/ directory

**Comment by a-schild** [comment]
Jave uses the system temp location

https://github.com/a-schild/jave2/blob/master/jave-core/src/main/java/ws/schild/jave/process/ffmpeg/DefaultFFMPEGLocator.java

Line 57
`File dirFolder = new File(System.getProperty("java.io.tmpdir"), "jave/");`

So you can either set another temp location in the properties of the JVM, or implement you own `DefaultFFMPEGLocator` class, which point's to the location you desire

**Comment by a-schild** [comment]
Fixed on `develop`. This has the same root cause as #281, and there were two races involved.

The extracted binary was made executable by handing the job to `/bin/chmod` through `Runtime.exec`, which starts the process without waiting for it, so ffmpeg could be launched before the permissions were set. On top of that, the binary was copied straight onto its final path, which makes it visible from its first byte, so a second JVM that only checks whether the path exists could run a half written file. Either one gives `error=13` / 权限不够, or `Cannot run program`.

The executable bit is now set in process with `File.setExecutable`, and the copy is staged in a temporary file that is made executable and only then moved into place atomically.

The change is on the `develop` branch, commit 9a0b8da, and is published as a snapshot so you can try it before 3.6.0 is released:

```xml
<repositories>
    <repository>
        <id>central-snapshots</id>
        <url>https://central.sonatype.com/repository/maven-snapshots/</url>
        <releases><enabled>false</enabled></releases>
        <snapshots><enabled>true</enabled></snapshots>
    </repository>
</repositories>

<dependency>
    <groupId>ws.schild</groupId>
    <artifactId>jave-all-deps</artifactId>
    <version>3.6.0-SNAPSHOT</version>
</dependency>
```

Feedback before this goes into the 3.6.0 release is welcome.

**Comment by a-schild** [comment]
Released in [3.6.0](https://github.com/a-schild/jave2/releases/tag/3.6.0), which is now on Maven Central:

```xml
<dependency>
    <groupId>ws.schild</groupId>
    <artifactId>jave-all-deps</artifactId>
    <version>3.6.0</version>
</dependency>
```

Closing this. Please reopen if you still run into it on 3.6.0.
