### ISSUE TITLE
`InputFormatException` while retrieving video information

### ISSUE THREAD

**Issue by rob93c** [a-schild/jave2#250]
Hello, I developed a Telegram bot capable of converting images and videos in Telegram stickers and to do so I use Jave2 with FFmpeg 6.1

I noticed that sometimes the code `new MultimediaObject(file, FFMPEG_LOCATOR).getInfo()` throws an `InputFormatException`:

```java
Caused by: ws.schild.jave.InputFormatException: null
at ws.schild.jave.MultimediaObject.parseMultimediaInfo(MultimediaObject.java:422)
at ws.schild.jave.MultimediaObject.getInfo(MultimediaObject.java:171)
at com.github.stickerifier.stickerify.media.MediaHelper.retrieveMultimediaInfo(MediaHelper.java:319)
```

I tried reading the video information using `ffprobe` and the output was the following:

```sh
ffprobe .\malformed
ffprobe version 6.1-full_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[matroska,webm @ 000001fc7f319780] Duplicate element
[matroska,webm @ 000001fc7f319780] 0x00 at pos 100 (0x64) invalid as first byte of an EBML number
[matroska,webm @ 000001fc7f319780] Duplicate element
[matroska,webm @ 000001fc7f319780] 0x00 at pos 169 (0xa9) invalid as first byte of an EBML number
[matroska,webm @ 000001fc7f319780] Element at 0x5d ending at 0x2cec0100000066 exceeds containing master element ending at 0x1409
.\malformed: End of file
```

I created a unit test to show its behavior: https://github.com/Stickerifier/Stickerify/blob/malformed-video-bug/src/test/java/com/github/stickerifier/stickerify/media/MediaHelperTest.java#L230-L235
The file affected by this issue is [here](https://github.com/Stickerifier/Stickerify/blob/malformed-video-bug/src/test/resources/malformed).

Let me know if there is anything else I can do to help investigating this issue.

**Comment by a-schild** [comment]
Hello @rob93c ,
thanks for reporting this.
The problem is very common, since there exist many many broken video files out into the wild.
The sample file you linked to the issu is such an example.
It looks like a webm file, but ffmpeg and ffprobe are not able to detect the correct details of the video/audio file and therefore it return null.
Also I'm not able to open/playback the file with vlc player and a few others, so it seems to be badly broken.

Did you expect jave2 to behave differently?

**Comment by rob93c** [comment]
Given the file is broken I would expect for the exception to highlight it, if possible; I think `InputFormatException: null` might be too generic in this case

Thanks for looking into this @a-schild! Feel free to close the issue if you don't need it

**Comment by captain-miao** [comment]
### have a try

To resolve the DNS resolution loss issue when using `ffmpeg` with `glibc`, you can use `nscd` (Name Service Cache Daemon). `nscd` is a daemon that provides a cache for the most common name service requests, improving DNS resolution performance and reliability.

Here are the steps to resolve the issue:

1. **Install `nscd` (if not already installed):**
   - On Debian-based systems (like Ubuntu), you can install `nscd` using the following command:
     ```bash
     sudo apt-get install nscd
     ```
   - On Red Hat-based systems (like CentOS), you can install `nscd` using the following command:
     ```bash
     sudo yum install nscd
     ```

2. **Start the `nscd` service:**
   - Use the following command to start the `nscd` service:
     ```bash
     sudo service nscd start
     ```

3. **Configure `nscd` (optional):**
   - You can configure `nscd` by editing the `/etc/nscd.conf` file to set cache sizes and timeout values according to your needs.

By following these steps, you can effectively address the DNS resolution loss issue when using `ffmpeg` with `glibc`, enhancing the stability and performance of DNS resolution.

**Comment by a-schild** [comment]
Closing this as part of a tidy up before 4.0.0, not because it was judged invalid.

This predates a substantial rework. The bundled ffmpeg has gone from 4.4 to 9.0.1 on every platform, the linux binaries are now built from source and linked statically against musl rather than taken from a publisher, and several long standing faults were fixed along the way, among them `-vol` and `-vsync` being sent to an ffmpeg that had removed them, a race that could run the extracted binary before it was executable, and `getSupportedEncodingFormats` silently returning nothing on any modern ffmpeg.

There is a fair chance the behaviour here is simply gone. There is also no reproducer on file and no way to tell from here.

**If it still happens on 4.0.0, please reopen** — the issue keeps its history and I would rather look at a live problem than leave a years old report sitting open. A short reproducer, the platform, and the exception would be plenty.
