### ISSUE TITLE
EncoderException IO exception

### ISSUE THREAD

**Issue by rayacode** [a-schild/jave2#261]
scenario for reproducing the exception, in javafx app, create a Service<t>, in service call method use converter class which instantiates a Encoder and uses it's encode method to convert the file, in ui user can use cancell button to cancel the convert in middle of happening when button action event happens service.cancel is called which is overiden and it calls converter class abortencoding which calls encoder abortencoding, convert cancels successfully (but sometimes ffmpeg task doesn't end successfully and continue to convert and only can be canceled by windows task manager) and this exception 
`ws.schild.jave.EncoderException: java.io.IOException: Stream Closed
	at jave.core@3.4.0/ws.schild.jave.Encoder.encode(Encoder.java:647)
	at jave.core@3.4.0/ws.schild.jave.Encoder.encode(Encoder.java:487)
	at jave.core@3.4.0/ws.schild.jave.Encoder.encode(Encoder.java:353)
	at .....Converter.convert(Converter.java:62)
	at .....conversion.ConversionService$ConversionTask.call(ConversionService.java:66)
	at .....conversion.ConversionService$ConversionTask.call(ConversionService.java:49)
	at javafx.graphics@22-ea/javafx.concurrent.Task$TaskCallable.call(Task.java:1399)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.graphics@22-ea/javafx.concurrent.Service.lambda$executeTask$6(Service.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@22-ea/javafx.concurrent.Service.lambda$executeTask$7(Service.java:723)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Stream Closed
	at java.base/java.io.FileInputStream.readBytes(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:276)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
	at jave.core@3.4.0/ws.schild.jave.utils.RBufferedReader.readLine(RBufferedReader.java:54)
	at jave.core@3.4.0/ws.schild.jave.Encoder.encode(Encoder.java:628)
	... 13 more`
exception throughs here 
`@Override
  public String readLine() throws IOException {
    if (lines.size() > 0) {
      return lines.remove(0);
    } else {
      return super.readLine();
    }
  }`
  at " return super.readLine();" line
  for instance in my app each conversionservic has it's own instance of the converter class so no one encoder is used for all files being converted instead each has their own service and encoder.
  
  `	at .....conversion.ConversionService$ConversionTask.call(ConversionService.java:66)` this calls converter class convert which calls encoder.encode in a try body with catching Exception

**Comment by rayacode** [comment]
I think here can turn to this to resolve the problem
`
public String readLine() throws IOException {
    if (lines.size() > 0) {
      return lines.remove(0);
    } else {
      try {
        return super.readLine();
      }catch (IOException e){
        throw new StremClosedIoException("Stream is closed while reading the line: ", e);
      }
      return null;
    }
  }
`

**Comment by a-schild** [comment]
Ok, to close the issue,
or do you have time to look into the real cause and provide a pull request?

**Comment by rayacode** [comment]
i will be back on the issue, first i have to finish the converter, i already tried new version of ffmpeg with jave, also i successfully added android build but version difference would be there with the version in desktop usage. i will create pull request on all these after the converter ends up.
