### ISSUE TITLE
Converting any audio with new Java2 fails

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#6]
So i just forked the project to test it https://github.com/GOXR3PLUS-STUDIO/jave2 and [published a release](https://github.com/GOXR3PLUS-STUDIO/jave2/releases) to use it with a random Maven project https://jitpack.io/#GOXR3PLUS-STUDIO/jave2/2.3 .

Then in the random Maven Project i added jave2 as a dependency , excluding the jars that are not needed ( i kept only windows64 , like : 

``` XML
<dependency>                                                                                               
<groupId>com.github.GOXR3PLUS-STUDIO.jave2</groupId>                                                   
<artifactId>jave-all-deps</artifactId>                                                                 
<version>2.3</version>                                                                                 
<exclusions>                                                                                           
	<exclusion>                                                                                        
		<groupId>com.github.GOXR3PLUS-STUDIO.jave2</groupId> <!-- Exclude Project-E from Project-B --> 
			<artifactId>jave-native-win32</artifactId>                                                    
	</exclusion>                                                                                       
	<exclusion>                                                                                        
		<groupId>com.github.GOXR3PLUS-STUDIO.jave2</groupId> <!-- Exclude Project-E from Project-B --> 
			<artifactId>jave-native-linux32</artifactId>                                                  
	</exclusion>                                                                                       
	<exclusion>                                                                                        
		<groupId>com.github.GOXR3PLUS-STUDIO.jave2</groupId> <!-- Exclude Project-E from Project-B --> 
			<artifactId>jave-native-linux64</artifactId>                                                  
	</exclusion>                                                                                       
	<exclusion>                                                                                        
		<groupId>com.github.GOXR3PLUS-STUDIO.jave2</groupId> <!-- Exclude Project-E from Project-B --> 
			<artifactId>jave-native-osx64</artifactId>                                                    
	</exclusion>                                                                                       
</exclusions>                                                                                          
</dependency>                                                                                              
```

So , the below error appears no matter which extension i try ... 

![screenshot_5](https://user-images.githubusercontent.com/20374208/41493819-fc51acbe-7113-11e8-8ad4-5db228b0f1ca.png)

**Comment by goxr3plus** [comment]
The error : 

``` XML

it.sauronsoftware.jave.EncoderException: size=     156kB time=00:00:09.92 bitrat
e= 128.7kbits/s speed=19.1x    
Finished
	at it.sauronsoftware.jave.Encoder.encode(Encoder.java:635)
	at javeConverter.Jave2Converter.convert(Jave2Converter.java:66)
	at javeConverter.Jave2Converter.<init>(Jave2Converter.java:43)
	at javeConverter.Jave2Converter.main(Jave2Converter.java:76)


```

**Comment by a-schild** [comment]
I need to be able to reproduce it, can you please make a complete test case, or at least show the conversion parameters your are using?

**Comment by a-schild** [comment]
The latest version contains the fix to corecctly process the ffpen output when doing audio only conversion
