### ISSUE TITLE
转码抛出异常，原视频是存在的（dav）ws.schild.jave.InputFormatException: Invalid data found when processing input

### ISSUE THREAD

**Issue by xujing1123** [a-schild/jave2#64]
ws.schild.jave.InputFormatException: Invalid data found when processing input
	at ws.schild.jave.MultimediaObject.parseMultimediaInfo(MultimediaObject.java:246) ~[jave-core-2.6.0.jar:na]
	at ws.schild.jave.MultimediaObject.getInfo(MultimediaObject.java:187) ~[jave-core-2.6.0.jar:na]
	at ws.schild.jave.Encoder.encode(Encoder.java:651) ~[jave-core-2.6.0.jar:na]
	at ws.schild.jave.Encoder.encode(Encoder.java:398) ~[jave-core-2.6.0.jar:na]
	at ws.schild.jave.Encoder.encode(Encoder.java:363) ~[jave-core-2.6.0.jar:na]
	at com.ht.util.VideoUtils.davToMp4(VideoUtils.java:44) ~[classes/:na]
	at com.ht.modules.sys.service.impl.FileInfoServiceImpl.uploadFile(FileInfoServiceImpl.java:77) [classes/:na]
	at com.ht.modules.sys.service.impl.FileInfoServiceImpl$$FastClassBySpringCGLIB$$34c37833.invoke(<generated>) [classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) [spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at com.ht.modules.sys.service.impl.FileInfoServiceImpl$$EnhancerBySpringCGLIB$$9536eeb7.uploadFile(<generated>) [classes/:na]
	at com.ht.modules.drive.dh.listener.DhVideoListener.onDownLoad(DhVideoListener.java:146) [classes/:na]
	at com.ht.modules.drive.dh.callback.DownLoadFileCallback.invoke(DownLoadFileCallback.java:29) [classes/:na]
	at sun.reflect.GeneratedMethodAccessor178.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:444) [jna-1.0.jar:3.4.0 (b5)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:474) [jna-1.0.jar:3.4.0 (b5)]

**Comment by a-schild** [comment]
Sounds like a corrupt inputfile.
Can you attach the inputfile and also the encoding parameters you did use?

**Comment by xujing1123** [comment]
AudioAttributes audio = new AudioAttributes();
        // 音频编码格式
        audio.setCodec("libmp3lame");
        // 音频比特率
        audio.setBitRate(800000);
        // 1 =单声道，2 =立体声
        audio.setChannels(1);
        VideoAttributes video = new VideoAttributes();
        // 视频编码格式
        video.setCodec("libx264");
        // 视频比特率
        video.setBitRate(3200000);
        // 数字设置小了，视频会卡顿
        video.setFrameRate(15);
        EncodingAttributes attrs = new EncodingAttributes();
        // 设置转换的类型
        attrs.setFormat("mp4");
        attrs.setAudioAttributes(audio);
        attrs.setVideoAttributes(video);

**Comment by a-schild** [comment]
The input file please, or try with another video file, I thinkl your source file is corrupt

**Comment by xujing1123** [comment]
But it doesn't break and it still works

**Comment by a-schild** [comment]
The input file please, your source file is corrupt in some ways which is causing ffmpeg to show these errors.

**Comment by a-schild** [comment]
Closing because of lack of answers
