### ISSUE TITLE
java.io.IOException: Cannot run program "/tmp/jave/ffmpeg-amd64-2.7.3": error=13, Permission denied

### ISSUE THREAD

**Issue by lintingjie** [a-schild/jave2#84]
We use k8s to deploy.This error occurs at the first request after deployment, subsequent requests will not report errors.But the error is not repeatable.Some deployments will happen, some will not.

Here is maven :
```
<dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-all-deps</artifactId>
            <version>2.7.3</version>
        </dependency>
```
code:
```
public static long getVideoDuration(String url) throws VodDurationException {
        try {
            URL u = new URL(url);
            MultimediaObject multimediaObject = new MultimediaObject(u);
            MultimediaInfo info = multimediaObject.getInfo();
            long duration = info.getDuration();
            return duration / 1000;
        }catch (Exception e){
            throw new VodDurationException(e.getMessage());
        }
    }
```

**Comment by a-schild** [comment]
Can you check if the file exists?
Are you starting multiple threads concurrently perhaps and so have a race condition?

**Comment by lintingjie** [comment]
Yes,it‘s running in multiple threads.’

**Comment by a-schild** [comment]
Can you check if the problem is gone, when the threads don't fire up at the same time? (Just for testing purposes)

**Comment by lintingjie** [comment]
Sorry,I check my code, it's not in a race condition.
I test it in a single thread and the error occurs too.（Although the probability of occurrence is very low）
```
Runtime.getRuntime().exec(new String[] {"/bin/chmod", "755", ffmpegFile.getAbsolutePath()});
```
I think this code my be the reason, because it executes in a separate process.
```
Executes the specified command and arguments in a separate process.
```

**Comment by a-schild** [comment]
Do you have a full stack trace?

**Comment by mressler** [comment]
Deployments to a particular environment should be outside the scope of the library. The users environment does not have an executable `ffmpeg` - if they provided one, this wouldn't be an issue.

I believe this library should not be responsible for providing `ffmpeg` binaries for a number of reasons. Not the least of which is complications like these.

**Comment by mressler** [comment]
No new information provided in a month and a half. Feel free to reopen if new information surfaces.

**Comment by ergenbao** [comment]
I’ve encountered the same problem too.


ws.schild.jave.EncoderException: java.io.IOException: Cannot run program "/tmp/jave/ffmpeg-amd64-2.7.3": error=13, Permission denied
	at ws.schild.jave.MultimediaObject.getInfo(MultimediaObject.java:175)
	at com.yqg.collection.core.utils.FFmpegUtil.getAudioDuration(FFmpegUtil.java:58)
	at com.yqg.collection.scheduler.jobs.col.enterpriseWeChat.ColWeChatMessageAudioJob.generateVoiceDurationByFileKey(ColWeChatMessageAudioJob.java:148)
	at com.yqg.collection.scheduler.jobs.col.enterpriseWeChat.ColWeChatMessageAudioJob.lambda$updateWeChatMessageVoiceDuration$1(ColWeChatMessageAudioJob.java:116)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:899)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.yqg.collection.scheduler.jobs.col.enterpriseWeChat.ColWeChatMessageAudioJob.updateWeChatMessageVoiceDuration(ColWeChatMessageAudioJob.java:123)
	at com.yqg.collection.scheduler.jobs.col.enterpriseWeChat.ColWeChatMessageAudioJob.doExecute(ColWeChatMessageAudioJob.java:75)
	at com.yqg.scheduler.executor.job.BaseJob.execute(BaseJob.java:19)
	at com.yqg.scheduler.executor.ExecutorTask.run(ExecutorTask.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "/tmp/jave/ffmpeg-amd64-2.7.3": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at ws.schild.jave.FFMPEGExecutor.execute(FFMPEGExecutor.java:119)
	at ws.schild.jave.FFMPEGExecutor.execute(FFMPEGExecutor.java:141)
	at ws.schild.jave.MultimediaObject.getInfo(MultimediaObject.java:172)
	... 21 common frames omitted
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 26 common frames omitted

**Comment by a-schild** [comment]
You are using a completely outdated version.
The new 3.x version has improved handling for such caces.

And if using SELinux, either whitelist it or turn SELinux off

**Comment by ergenbao** [comment]
got it  thanks
