### ISSUE TITLE
Allow more ffmpeg flags

### ISSUE THREAD

**Issue by ChiranjibKarn** [a-schild/jave2#90]
I do not find a way to use additional flags like **crf**, **preset**, **tune** etc. Is there any plan to allow these (or more) flags?

**Comment by a-schild** [comment]
A patch request will be gladly accepted

**Comment by ChiranjibKarn** [comment]
Sure, I will send a pull request. But currently am busy with other stuff on my table.

**Comment by mressler** [comment]
Closed with the custom flags pull request.

@a-schild I can't close this - can you close it if you agree?

**Comment by a-schild** [comment]
I did push all changes/reworks for the 3.0, including updated pom.xml files.
Now many test cases in java-core-test fail with and `stream already closed`message

```
Exception in thread "Thread-2" java.lang.IllegalStateException: stream has already been operated upon or closed
	at java.base/java.util.stream.AbstractPipeline.sourceStageSpliterator(AbstractPipeline.java:279)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at ws.schild.jave.Encoder.encode(Encoder.java:532)
	at ws.schild.jave.Encoder.encode(Encoder.java:421)
	at ws.schild.jave.EncoderTest.lambda$testAbortEncoder$0(EncoderTest.java:138)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Either the tests need to be updated or we have some race condition there

**Comment by mressler** [comment]
I'll take a look.

**Comment by mressler** [comment]
Most recent PR will fix this issue. Sorry about that. I did not pick that up on isolated tests. I'll run them all next time.

**Comment by ChiranjibKarn** [comment]
@mressler I do not see '-crf' option there. Remember, -qscale:v argument get ignored when you use video codec 'libx264', the recommended argument is '-crf'

**Comment by mressler** [comment]
The request was to support more ffmpeg arguments. The new system will allow for end users to add any argument to the encoder.

We will gladly accept a pull request to add those particular options to the [`EncodingAttributes`](https://github.com/a-schild/jave2/blob/dev-3.0-changes/jave-core/src/main/java/ws/schild/jave/encode/EncodingAttributes.java), [`VideoAttributes`](https://github.com/a-schild/jave2/blob/dev-3.0-changes/jave-core/src/main/java/ws/schild/jave/encode/VideoAttributes.java), or [`AudioAttributes`](https://github.com/a-schild/jave2/blob/dev-3.0-changes/jave-core/src/main/java/ws/schild/jave/encode/AudioAttributes.java)
