### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by FelipeGerolomo** [a-schild/jave2#94]
In Windows environment works but in Linux not

`2020-07-17 17:29:04,429 ERROR [stderr] (default task-15) ws.schild.jave.EncoderException: java.io.IOException: Cannot run program "/tmp/jave/ffmpeg-amd64-2.7.3": error=13, Permission denied
2020-07-17 17:29:04,430 ERROR [stderr] (default task-15) 	at ws.schild.jave.Encoder.encode(Encoder.java:640)
2020-07-17 17:29:04,430 ERROR [stderr] (default task-15) 	at ws.schild.jave.Encoder.encode(Encoder.java:398)
2020-07-17 17:29:04,430 ERROR [stderr] (default task-15) 	at ws.schild.jave.Encoder.encode(Encoder.java:363)
2020-07-17 17:29:04,430 ERROR [stderr] (default task-15) 	at br.edu.unicesumar.conteudo.controller.resource.ConteudoController.uploadAudio(ConteudoController.java:111)
2020-07-17 17:29:04,430 ERROR [stderr] (default task-15) 	at br.edu.unicesumar.conteudo.controller.resource.ConteudoController$Proxy$_$$_WeldClientProxy.uploadAudio(Unknown Source)
2020-07-17 17:29:04,430 ERROR [stderr] (default task-15) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-17 17:29:04,430 ERROR [stderr] (default task-15) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-17 17:29:04,431 ERROR [stderr] (default task-15) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-17 17:29:04,431 ERROR [stderr] (default task-15) 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-07-17 17:29:04,431 ERROR [stderr] (default task-15) 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
2020-07-17 17:29:04,431 ERROR [stderr] (default task-15) 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
2020-07-17 17:29:04,431 ERROR [stderr] (default task-15) 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
2020-07-17 17:29:04,431 ERROR [stderr] (default task-15) 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
2020-07-17 17:29:04,431 ERROR [stderr] (default task-15) 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
2020-07-17 17:29:04,431 ERROR [stderr] (default task-15) 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
2020-07-17 17:29:04,431 ERROR [stderr] (default task-15) 	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
2020-07-17 17:29:04,431 ERROR [stderr] (default task-15) 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2020-07-17 17:29:04,432 ERROR [stderr] (default task-15) 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
2020-07-17 17:29:04,433 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
2020-07-17 17:29:04,434 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
2020-07-17 17:29:04,434 ERROR [stderr] (default task-15) 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
2020-07-17 17:29:04,434 ERROR [stderr] (default task-15) 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
2020-07-17 17:29:04,434 ERROR [stderr] (default task-15) 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
2020-07-17 17:29:04,434 ERROR [stderr] (default task-15) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-07-17 17:29:04,434 ERROR [stderr] (default task-15) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-07-17 17:29:04,434 ERROR [stderr] (default task-15) 	at java.lang.Thread.run(Thread.java:748)
2020-07-17 17:29:04,434 ERROR [stderr] (default task-15) Caused by: java.io.IOException: Cannot run program "/tmp/jave/ffmpeg-amd64-2.7.3": error=13, Permission denied
2020-07-17 17:29:04,435 ERROR [stderr] (default task-15) 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
2020-07-17 17:29:04,435 ERROR [stderr] (default task-15) 	at java.lang.Runtime.exec(Runtime.java:620)
2020-07-17 17:29:04,435 ERROR [stderr] (default task-15) 	at java.lang.Runtime.exec(Runtime.java:485)
2020-07-17 17:29:04,435 ERROR [stderr] (default task-15) 	at ws.schild.jave.FFMPEGExecutor.execute(FFMPEGExecutor.java:119)
2020-07-17 17:29:04,435 ERROR [stderr] (default task-15) 	at ws.schild.jave.FFMPEGExecutor.execute(FFMPEGExecutor.java:141)
2020-07-17 17:29:04,435 ERROR [stderr] (default task-15) 	at ws.schild.jave.Encoder.encode(Encoder.java:637)
2020-07-17 17:29:04,435 ERROR [stderr] (default task-15) 	... 45 more
2020-07-17 17:29:04,435 ERROR [stderr] (default task-15) Caused by: java.io.IOException: error=13, Permission denied
2020-07-17 17:29:04,435 ERROR [stderr] (default task-15) 	at java.lang.UNIXProcess.forkAndExec(Native Method)
2020-07-17 17:29:04,436 ERROR [stderr] (default task-15) 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
2020-07-17 17:29:04,436 ERROR [stderr] (default task-15) 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
2020-07-17 17:29:04,436 ERROR [stderr] (default task-15) 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
2020-07-17 17:29:04,436 ERROR [stderr] (default task-15) 	... 50 more`

**Comment by a-schild** [comment]
When you look at the /tmp/jave/ folder:
- Is there a ffmpeg-amd-2.7.3 file existing?
- Hast this file execure rights?
- Can you start it from the command line?
- Is perhaps SELINUX enabled, which prevents running apps from /tmp folder?
- Have you a java policy active, which prevents this from running?

**Comment by FelipeGerolomo** [comment]
Is there a ffmpeg-amd-2.7.3 file existing? Yes
Hast this file execure rights? Yes
Can you start it from the command line? No
Is perhaps SELINUX enabled, which prevents running apps from /tmp folder? No
Have you a java policy active, which prevents this from running? No

**Comment by a-schild** [comment]
In that case you have to debug why you can't start it from the command line.
There must be some sort of restriction on your linux system which prevents running the executable there...

**Comment by FelipeGerolomo** [comment]
The only way I found, is to create a symbolic link
cd /tmp/jave
mv -f ffmpeg-amd64-2.7.3 /usr/bin/
ln -s /usr/bin/ffmpeg-amd64-2.7.3 ffmpeg-amd64-2.7.3

**Comment by a-schild** [comment]
In that case your linux has some non-standard config which prevents running it from the /tmp folder.
Please look with your linux admin what's the cause for this

**Comment by mressler** [comment]
@a-schild This should be closed.

Another reason to not provide binaries in the library. This should be provided by the environment.

**Comment by a-schild** [comment]
The problem with the platform provided binaries is, that we don't know what version they have.

**Comment by mressler** [comment]
@a-schild great point.

I'm currently reworking the parsing of `ffmpeg` output. One of the things I'll be adding is an `ffmpeg` version detection so that multiple versions _could_ be supported by the same JAVE codebase.

When that effort is complete, we could warn or even error if we detect an unsupported version.

I would like to continue this discussion, but this particular issue should be closed since it's a local environment setup issue.
