### ISSUE TITLE
ws.schild.jave.InputFormatException when converting .mp3 to .wav file 

### ISSUE THREAD

**Issue by sadeepMihiranga** [a-schild/jave2#98]
I wrote a method that convert .mp3 files to .wav files. 
The method is working perfectly on my localhost (development computer).
```
import ws.schild.jave.AudioAttributes;
import ws.schild.jave.Encoder;
import ws.schild.jave.EncodingAttributes;
import ws.schild.jave.MultimediaObject;

private static String convertTempMp3asWavInTempFolder(String pTempMp3File, String pTempWavFile) 
	{
		 String __response = null;		 
		 File __sourceFile = null;
		 File __targetFile = null;
		 
		 AudioAttributes __audioAttributes = null;
		 EncodingAttributes __encodingAttributes = null;
		 
		 try
		 {
			 __sourceFile = new File(pTempMp3File);
			 __targetFile = new File(pTempWavFile);
			 
			 if (__sourceFile != null || __targetFile != null) 
			 {	        
				 try
				 {
                 	               __audioAttributes = new AudioAttributes();                
                	               __audioAttributes.setCodec("pcm_s16le");
                	               __audioAttributes.setBitRate(new Integer(16));
                	               __audioAttributes.setChannels(new Integer(2));
                	               __audioAttributes.setSamplingRate(new Integer(8000));
				    
				      __encodingAttributes = new EncodingAttributes();
				      __encodingAttributes.setFormat("wav");
				      __encodingAttributes.setAudioAttributes(__audioAttributes);						 
				    
				      new Encoder().encode(new MultimediaObject(__sourceFile), __targetFile, __encodingAttributes);
                  
                                       __response = "WROTE";
				 } 
				 catch (Exception e)
				 {
					 __response="ERROR_WHILE_WRITING_FILE";
					 e.printStackTrace();
				 }

			 }
		 }
		 catch(Exception e)
		 {
			 __response="ERROR_WHILE_WRITING_FILE";
			 e.printStackTrace();
		 }
		 finally
		 {
			 if(__audioAttributes != null)
				 __audioAttributes = null;
			 
			 if(__encodingAttributes != null)
				 __encodingAttributes = null;
			 
			 __sourceFile = null;
			 __targetFile = null;
		 }		

		return __response;
	}
```
When i deployed to the production environment (Linux server with Apache tomcat application server) it throws an Exception as bellow.

```
ws.schild.jave.InputFormatException
	at ws.schild.jave.MultimediaObject.parseMultimediaInfo(MultimediaObject.java:432)
	at ws.schild.jave.MultimediaObject.getInfo(MultimediaObject.java:187)
	at ws.schild.jave.Encoder.encode(Encoder.java:651)
	at ws.schild.jave.Encoder.encode(Encoder.java:398)
	at ws.schild.jave.Encoder.encode(Encoder.java:363)
	at lk.mobios.vibermessages.uploader.FileConvertor.convertTempMp3asWavInTempFolder(FileConvertor.java:257)
	at lk.mobios.vibermessages.uploader.FileConvertor.covertAndWrite(FileConvertor.java:102)
	at lk.mobios.vibermessages.uploader.AudioUploader.doPost(AudioUploader.java:72)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

Why is getting this exception ? I tried with several .mp3 files.

**Comment by a-schild** [comment]
Is the mp3 file received correctly in the post?
I think it gets a corrupted or partial upload

**Comment by sadeepMihiranga** [comment]
> Is the mp3 file received correctly in the post?
> I think it gets a corrupted or partial upload

**Comment by a-schild** [comment]
Can you share the uploaded file with us?

**Comment by sadeepMihiranga** [comment]
[[Waploaded]_Lil_Wayne_-_A_Milli-1539795103.zip](https://github.com/a-schild/jave2/files/4959110/Waploaded._Lil_Wayne_-_A_Milli-1539795103.zip)

Here is one of the file that i was uploaded.

**Comment by a-schild** [comment]
I did test it with the file you provided and the conversion to wav works fine

```
       File source = new File(getResourceSourcePath(), "audio-test06.mp3");
        File target = new File(getResourceTargetPath(), "audio-test06.wav");
        if (target.exists())
        {
            target.delete();
        }
        
        Encoder encoder = new Encoder();
        AudioAttributes audio = new AudioAttributes();
        audio.setCodec("pcm_s16le");
        audio.setBitRate(16);
        audio.setChannels(2);
        audio.setSamplingRate(8000);
				    
        EncodingAttributes attrs = new EncodingAttributes();
        attrs.setFormat("wav");
        attrs.setAudioAttributes(audio);	        
        encoder.encode(new MultimediaObject(source), target, attrs);
```

**Comment by a-schild** [comment]
Do you use the current version of jave?

**Comment by sadeepMihiranga** [comment]
> Do you use the current version of jave?

I'm using 2.7.3 version.

**Comment by a-schild** [comment]
I thik you have some other problem here, since it does not throw that error with the file you provided.
You can turn on more logging on the MultimediaObject on Debug/Trace level and see what messages it struggels with

**Comment by mressler** [comment]
@a-schild This should be closed unless more information resurfaces.

**Comment by mressler** [comment]
Closing. No new information was provided.
